-- -- 00003_client_roles_seed.sql
-- -- CLIENT DATABASE MIGRATION - Seed roles that match billing products
-- -- Run this in your application database AFTER running 00002_billing_user_roles_interface.up.sql

-- BEGIN;

-- -- Create roles table if it doesn't exist (for new installations)
-- CREATE TABLE IF NOT EXISTS roles (
--     id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
--     slug TEXT NOT NULL UNIQUE,
--     name TEXT NOT NULL,
--     description TEXT,
--     permissions JSONB DEFAULT '{}',
--     is_active BOOLEAN NOT NULL DEFAULT true,
--     created_at TIMESTAMPTZ NOT NULL DEFAULT current_timestamp,
--     updated_at TIMESTAMPTZ NOT NULL DEFAULT current_timestamp
-- );

-- CREATE INDEX IF NOT EXISTS idx_roles_slug ON roles(slug);
-- CREATE INDEX IF NOT EXISTS idx_roles_is_active ON roles(is_active);

-- -- Insert roles that correspond to billing products
-- INSERT INTO roles (slug, name, description, permissions) VALUES
-- (
--     'basic',
--     'Basic Member',
--     'Standard access to content library and community features',
--     '{
--         "content": {
--             "view_standard": true,
--             "download_standard": true,
--             "stream_quality": "720p",
--             "concurrent_streams": 1
--         },
--         "community": {
--             "post_comments": true,
--             "create_threads": true,
--             "private_messages": false
--         },
--         "features": {
--             "bookmarks": 10,
--             "playlists": 3,
--             "offline_downloads": false
--         }
--     }'::jsonb
-- ),
-- (
--     'premium',
--     'Premium Member',
--     'Full access to exclusive content with enhanced features',
--     '{
--         "content": {
--             "view_standard": true,
--             "view_premium": true,
--             "download_standard": true,
--             "download_premium": true,
--             "stream_quality": "1080p",
--             "concurrent_streams": 3,
--             "early_access": true
--         },
--         "community": {
--             "post_comments": true,
--             "create_threads": true,
--             "private_messages": true,
--             "custom_avatar": true,
--             "profile_badge": "premium"
--         },
--         "features": {
--             "bookmarks": 100,
--             "playlists": 20,
--             "offline_downloads": true,
--             "ad_free": true,
--             "priority_support": true
--         }
--     }'::jsonb
-- ),
-- (
--     'creator',
--     'Content Creator',
--     'Full premium access plus creator tools and monetization',
--     '{
--         "content": {
--             "view_standard": true,
--             "view_premium": true,
--             "view_creator": true,
--             "download_standard": true,
--             "download_premium": true,
--             "download_creator": true,
--             "stream_quality": "4k",
--             "concurrent_streams": 5,
--             "early_access": true
--         },
--         "creator": {
--             "upload_content": true,
--             "monetization": true,
--             "analytics": true,
--             "custom_pricing": true,
--             "bulk_upload": true,
--             "schedule_releases": true,
--             "revenue_share": 0.7
--         },
--         "community": {
--             "post_comments": true,
--             "create_threads": true,
--             "private_messages": true,
--             "custom_avatar": true,
--             "profile_badge": "creator",
--             "verified_checkmark": true
--         },
--         "features": {
--             "bookmarks": "unlimited",
--             "playlists": "unlimited",
--             "offline_downloads": true,
--             "ad_free": true,
--             "priority_support": true,
--             "api_access": true,
--             "custom_branding": true
--         }
--     }'::jsonb
-- ),
-- (
--     'enterprise',
--     'Enterprise Member',
--     'Business features with team management and API access',
--     '{
--         "content": {
--             "view_standard": true,
--             "view_premium": true,
--             "view_creator": true,
--             "view_enterprise": true,
--             "download_standard": true,
--             "download_premium": true,
--             "download_creator": true,
--             "download_enterprise": true,
--             "stream_quality": "4k",
--             "concurrent_streams": "unlimited",
--             "early_access": true
--         },
--         "enterprise": {
--             "team_management": true,
--             "sso_integration": true,
--             "custom_domain": true,
--             "white_label": true,
--             "bulk_licenses": true,
--             "usage_reports": true,
--             "invoice_billing": true,
--             "sla_guarantee": true
--         },
--         "api": {
--             "full_access": true,
--             "rate_limit": "10000/hour",
--             "webhooks": true,
--             "custom_integrations": true
--         },
--         "community": {
--             "post_comments": true,
--             "create_threads": true,
--             "private_messages": true,
--             "custom_avatar": true,
--             "profile_badge": "enterprise",
--             "verified_checkmark": true
--         },
--         "features": {
--             "bookmarks": "unlimited",
--             "playlists": "unlimited",
--             "offline_downloads": true,
--             "ad_free": true,
--             "priority_support": true,
--             "dedicated_support": true,
--             "api_access": true,
--             "custom_branding": true,
--             "training_sessions": true
--         }
--     }'::jsonb
-- )
-- ON CONFLICT (slug) DO UPDATE SET
--     name = EXCLUDED.name,
--     description = EXCLUDED.description,
--     permissions = EXCLUDED.permissions,
--     updated_at = current_timestamp;

-- -- Additional utility roles (not tied to billing)
-- INSERT INTO roles (slug, name, description, permissions) VALUES
-- (
--     'trial',
--     'Trial User',
--     'Limited trial access to evaluate the platform',
--     '{
--         "content": {
--             "view_standard": true,
--             "download_standard": false,
--             "stream_quality": "480p",
--             "concurrent_streams": 1,
--             "daily_limit": 5
--         },
--         "community": {
--             "post_comments": false,
--             "create_threads": false,
--             "private_messages": false
--         },
--         "features": {
--             "bookmarks": 3,
--             "playlists": 1,
--             "offline_downloads": false,
--             "trial_days_remaining": true
--         }
--     }'::jsonb
-- ),
-- (
--     'suspended',
--     'Suspended User',
--     'Account suspended for violation or payment issues',
--     '{
--         "content": {
--             "view_standard": false,
--             "download_standard": false
--         },
--         "community": {
--             "post_comments": false,
--             "create_threads": false,
--             "private_messages": false
--         },
--         "features": {
--             "account_recovery": true
--         }
--     }'::jsonb
-- ),
-- (
--     'moderator',
--     'Community Moderator',
--     'Community moderation privileges',
--     '{
--         "moderation": {
--             "delete_comments": true,
--             "ban_users": true,
--             "pin_threads": true,
--             "review_reports": true
--         },
--         "content": {
--             "view_standard": true,
--             "view_premium": true,
--             "stream_quality": "1080p"
--         },
--         "community": {
--             "post_comments": true,
--             "create_threads": true,
--             "private_messages": true,
--             "profile_badge": "moderator"
--         }
--     }'::jsonb
-- )
-- ON CONFLICT (slug) DO UPDATE SET
--     name = EXCLUDED.name,
--     description = EXCLUDED.description,
--     permissions = EXCLUDED.permissions,
--     updated_at = current_timestamp;

-- -- Create a view for easy role checking
-- CREATE OR REPLACE VIEW active_user_roles AS
-- SELECT 
--     ur.user_id,
--     r.slug as role_slug,
--     r.name as role_name,
--     r.permissions,
--     ur.created_at as granted_at,
--     ur.updated_at as last_modified
-- FROM user_roles ur
-- JOIN roles r ON ur.role_id = r.id
-- WHERE r.is_active = true;

-- COMMENT ON VIEW active_user_roles IS 'Simplified view of active user roles with permissions';

-- -- Function to check if user has a specific permission
-- CREATE OR REPLACE FUNCTION user_has_permission(
--     p_user_id UUID,
--     p_permission_path TEXT  -- e.g., 'content.view_premium' or 'creator.upload_content'
-- ) RETURNS BOOLEAN
-- LANGUAGE plpgsql
-- AS $$
-- DECLARE
--     v_has_permission BOOLEAN := false;
--     v_path_parts TEXT[];
-- BEGIN
--     -- Split the permission path
--     v_path_parts := string_to_array(p_permission_path, '.');
    
--     -- Check if user has the permission in any of their roles
--     SELECT EXISTS(
--         SELECT 1 
--         FROM active_user_roles
--         WHERE user_id = p_user_id
--         AND CASE array_length(v_path_parts, 1)
--             WHEN 1 THEN (permissions->v_path_parts[1]) IS NOT NULL
--             WHEN 2 THEN (permissions->v_path_parts[1]->v_path_parts[2])::boolean = true
--             WHEN 3 THEN (permissions->v_path_parts[1]->v_path_parts[2]->v_path_parts[3])::boolean = true
--             ELSE false
--         END
--     ) INTO v_has_permission;
    
--     RETURN v_has_permission;
-- END;
-- $$;

-- -- Function to get user's highest tier role
-- CREATE OR REPLACE FUNCTION get_user_tier(p_user_id UUID)
-- RETURNS TEXT
-- LANGUAGE plpgsql
-- AS $$
-- DECLARE
--     v_tier TEXT;
-- BEGIN
--     -- Return the highest tier role in order of precedence
--     SELECT COALESCE(
--         (SELECT 'enterprise' WHERE EXISTS(SELECT 1 FROM active_user_roles WHERE user_id = p_user_id AND role_slug = 'enterprise')),
--         (SELECT 'creator' WHERE EXISTS(SELECT 1 FROM active_user_roles WHERE user_id = p_user_id AND role_slug = 'creator')),
--         (SELECT 'premium' WHERE EXISTS(SELECT 1 FROM active_user_roles WHERE user_id = p_user_id AND role_slug = 'premium')),
--         (SELECT 'basic' WHERE EXISTS(SELECT 1 FROM active_user_roles WHERE user_id = p_user_id AND role_slug = 'basic')),
--         (SELECT 'trial' WHERE EXISTS(SELECT 1 FROM active_user_roles WHERE user_id = p_user_id AND role_slug = 'trial')),
--         'none'
--     ) INTO v_tier;
    
--     RETURN v_tier;
-- END;
-- $$;

-- COMMIT;