-- Grant system table permissions for monitoring and debugging
-- Runs via ch-migrate after cluster coordination is ready
GRANT ON CLUSTER doujins SELECT ON system.tables TO analytics_user;
GRANT ON CLUSTER doujins SELECT ON system.columns TO analytics_user;
GRANT ON CLUSTER doujins SELECT ON system.databases TO analytics_user;
GRANT ON CLUSTER doujins SELECT ON system.parts TO analytics_user;
GRANT ON CLUSTER doujins SELECT ON system.parts_columns TO analytics_user;
GRANT ON CLUSTER doujins SELECT ON system.mutations TO analytics_user;
GRANT ON CLUSTER doujins SELECT ON system.merges TO analytics_user;
GRANT ON CLUSTER doujins SELECT ON system.processes TO analytics_user;
